---
tags: ["Needs-Tests","alignment","data-analysis","data-science","flexible","pandas","python"]
title: "BUG: numpy.maximum(pandas.Timestamp(...), pandas.Series(..., dtype='datetime64')) fails with TypeError"
html_url: "https://github.com/pandas-dev/pandas/issues/50864"
user: "hottwaj"
repo: "pandas-dev/pandas"
---

